// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event4u.proto

package com.event4u.notificationservice.grpc;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>.APIResponse.ResponseType responseType = 2;</code>
   */
  int getResponseTypeValue();
  /**
   * <code>.APIResponse.ResponseType responseType = 2;</code>
   */
  com.event4u.notificationservice.grpc.APIResponse.ResponseType getResponseType();
}
