// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event4u.proto

package com.event4u.notificationservice.grpc;

public final class Event4U {
  private Event4U() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\revent4u.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\327\001\n\007Request\022-\n\ttimestamp\030\001 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\023\n\013serviceNa" +
      "me\030\002 \001(\t\022\016\n\006userId\030\003 \001(\003\022\'\n\nactionType\030\004" +
      " \001(\0162\023.Request.ActionType\022\024\n\014resourceNam" +
      "e\030\005 \001(\t\"9\n\nActionType\022\n\n\006CREATE\020\000\022\n\n\006DEL" +
      "ETE\020\001\022\007\n\003GET\020\002\022\n\n\006UPDATE\020\003\"\177\n\013APIRespons" +
      "e\022\027\n\017responseMessage\030\001 \001(\t\022/\n\014responseTy" +
      "pe\030\002 \001(\0162\031.APIResponse.ResponseType\"&\n\014R" +
      "esponseType\022\013\n\007SUCCESS\020\000\022\t\n\005ERROR\020\0012-\n\006a" +
      "ction\022#\n\tlogAction\022\010.Request\032\014.APIRespon" +
      "seB(\n$com.event4u.notificationservice.gr" +
      "pcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Timestamp", "ServiceName", "UserId", "ActionType", "ResourceName", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseType", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
