// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event4u.proto

package com.event4u.notificationservice.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>string serviceName = 2;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>string serviceName = 2;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>int64 userId = 3;</code>
   */
  long getUserId();

  /**
   * <code>.Request.ActionType actionType = 4;</code>
   */
  int getActionTypeValue();
  /**
   * <code>.Request.ActionType actionType = 4;</code>
   */
  com.event4u.notificationservice.grpc.Request.ActionType getActionType();

  /**
   * <code>string resourceName = 5;</code>
   */
  java.lang.String getResourceName();
  /**
   * <code>string resourceName = 5;</code>
   */
  com.google.protobuf.ByteString
      getResourceNameBytes();
}
